### ISSUE TITLE
Weapon disappeared

### ISSUE THREAD

**Issue by EricRomig** [smd111/LatentChecker#3]
Hello, 

This is the first time I used the program. I used the command // lc run just like the readme stated, it gave me the total ws points I had. When it did this, the pole disappeared from my character and is not longer showing in my inventory to equip. the screen says Starting.....then says done! Remember to re-dress yourself. I canceled the trials in attempt to get another weapon, but it says I already have the pole of trials, but again, it is no longer showing in my inventory. Please help...thakns

**Comment by Byrth** [comment]
This addon moves the weapon to one of your other inventories (sack) so it can read the WS points.

Check your bags. You probably still have the weapon.
